### ISSUE TITLE
batch size 1 out of memory during training on TITAN XP 12G

### ISSUE THREAD

**Issue by JunMa11** [HiLab-git/COPLE-Net#2]
Dear @taigw ,

Thanks for sharing the great work.

I'd like to train COPLE-Net with the 70 noisy-label cases.
Following is the config info.
```
[dataset]
# tensor type (float or double)
tensor_type = float


root_dir  = /path to/part1
train_csv = config/train/all.csv
valid_csv = config/train/valid.csv
test_csv  = config/test/test_all.csv

# modality number
modal_num = 1

# data transforms
# train_transform = [ChannelWiseNormalize, LabelConvert, RandomCrop, LabelToProbability]
# test_transform  = [ChannelWiseNormalize]
train_transform = [Pad, LabelToProbability]
test_transform  = [Pad]

# parameter of Pad
Pad_output_size = [1, 32, 32]
Pad_ceil_mode   = True
Pad_inverse     = True

ChannelWiseNormalize_mean = None
ChannelWiseNormalize_std  = None
ChannelWiseNormalize_channels = [0]
ChannelWiseNormalize_zero_to_random = False
ChannelWiseNormalize_inverse = False

LabelConvert_source_list = [0, 255]
LabelConvert_target_list = [0, 1]
LabelConvert_inverse = False

RandomCrop_output_size = [240, 240]
RandomCrop_foreground_focus = False
RandomCrop_foreground_ratio = None
RandomCrop_mask_label       = None
RandomCrop_inverse     = False

LabelToProbability_class_num = 2
LabelToProbability_inverse   = False
# =====================================================

[network]
# this section gives parameters for network
# In this example, a customized network is used.

[training]
# device name" cuda:n or cpu
device_name = cuda:1

batch_size    = 1
loss_function = noise_robust_dice_loss
noise_robust_dice_loss_p = 1.5
# for optimizers
optimizer     = Adam
learning_rate = 1e-4
momentum      = 0.9
weight_decay  = 1e-5

# for lr schedular (MultiStepLR)
lr_gamma      = 0.5
lr_milestones = [10000]

summary_dir       = model/coplenet
checkpoint_prefix = model/coplenet

# start iter
iter_start = 0
iter_max   = 200000
iter_valid = 1000
iter_save  = 10000
```

I set `batch_size    = 1`, and my GPU memory is empty (12G available for training).
However, it is wired that out of memory occurred.

```
RuntimeError: CUDA out of memory. Tried to allocate 184.00 MiB (GPU 1; 11.91 GiB total capacity; 11.29 GiB already allocated; 81.06 MiB free; 11.30 GiB reserved in total by PyTorch)
```

Would it be possible for you to tell me what's wrong with my settings?

Looking forward to your reply.

Best regards,
Jun

**Comment by taigw** [comment]
Hi Jun, @JunMa,
   You have disabled crop in "train_transform", so I guess your actual patch size  is the entire 3D volume, that's why you have error of "out of memory".

**Comment by JunMa11** [comment]
Hi Guotai, @taigw ,

Thanks for your quick reply very much.

I add crop in "train_transform", and the OOM problem is solved.

However, a new error occurred:

```
  File "/path to/python3.6/site-packages/pymic/io/transform3d.py", line 392, in __call__
    assert(input_dim == len(self.output_size))
AssertionError
```

It seems that I need to reformat the 3D nii files to 2D slices before training, right?

Sorry for so many "stupid" questions. Thanks for your time very much.

Best regards,
Jun

**Comment by JunMa11** [comment]
Hi @taigw 

I solve the problem by reformating the 3D nii files to 2D slices.

Following is my trained model with COPLE-Net.
I'm not sure whether I reproduce the performance of COPLE-Net.
Any comments would be highly appreciated.

链接：https://pan.baidu.com/s/16Vp4PQWEvx1BtgflD63w2g 
提取码：zf02

> Both training and validation sets are the 70 noisy-label cases.

Best regards,
Jun

**Comment by Leong1230** [comment]
> Hi @taigw
> 
> I solve the problem by reformating the 3D nii files to 2D slices.
> 
> Following is my trained model with COPLE-Net.
> I'm not sure whether I reproduce the performance of COPLE-Net.
> Any comments would be highly appreciated.
> 
> 链接：https://pan.baidu.com/s/16Vp4PQWEvx1BtgflD63w2g
> 提取码：zf02
> 
> > Both training and validation sets are the 70 noisy-label cases.
> 
> Best regards,
> Jun

Hi, the shared link is disabled. Do you mind sharing the config file again?
I also meet the OOM problem, and don't know how to modify the config info.

Thank you!

**Comment by JunMa11** [comment]
Hi @Leong1230 ,

Unfortunately, these files have been deleted.

**Comment by massimilianoporzio** [comment]
Please can anybody help me in finding the right order for crop and pad? I have a nifti image, First I have to randoCrop to something like 256x256 then Padding with a final dimension of 32x32?

**Comment by aatiqa-ghazali** [comment]
hi @Leong1230 for OOM memory problem you have to change some values in train_transform so instead of 
train_transform = [Pad, LabelToProbability]

it should be like  this 👍  train_transform = [RandomCrop,Pad, LabelToProbability]

rest of code will be same as mentioned above by @JunMa11

**Comment by aatiqa-ghazali** [comment]
@JunMa11  how did you format the 3D volumes to 2D slices? By using some tool or with some code ?
Sorry for asking this stupid question I am new in learning medical image segmentation.

**Comment by aatiqa-ghazali** [comment]
@massimilianoporzio  please explain your question
